Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/inventory_control/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fornecedores/', include('suppliers.urls')),
    path('produtos/', include('products.urls')),
    path('', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
    path("", views.index, name="index"),
    path("cadastro/", views.create, name="create"),
    path("<int:id>/delete", views.delete, name="delete"),
    path("search", views.search, name="search"),
    path("<int:id>/toggle_enabled", views.toggle_enabled, name="toggle_enabled"),
    path("categorias/", views.get_categories, name="categories"),
    path("categorias/cadastro/", views.create_category, name="category_create"),
    path("category/<int:id>/delete", views.delete_category, name="category_delete"),
    path("category/search", views.search_categories, name="categories_search"),
    path("categorias/<slug:slug>/", views.update_category, name="category_update"),
    path("<int:id>/suppliers/", views.get_suppliers_from_product, name = "suppliers"),
    path("<int:id>/delete_supplier/", views.delete_supplier_from_product, name='delete_supplier'),
    path("<slug:slug>/", views.update, name="update"),
]

Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/user/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("usuarios/", views.index, name="index"),
    path("usuarios/cadastro/", views.create, name="create"),
    path("login/", views.login, name="login"),
    path('usuarios/<str:username>/', views.update, name="update"),
    path('usuarios/<int:id>/', views.delete, name="delete"),
]

Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/user/models.py
from django.db import models

# Create your models here.

Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import validate_email

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'password', 'is_active']
        widgets = {
            'password': forms.PasswordInput()
        }
        
        
    def __init__ (self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        
    def save(self, commit=True):
        password = self.cleaned_data.get('password')
        
        user = super().save(commit=False)
        
        if password:
            user.set_password(password)
            
        if commit:
            user.save()
            
        return user
    
    def clean(self):
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        
        if first_name == last_name:
            self.add_error('first_name', ValidationError('O primeiro nome não pode igual ao sobrenome'))
            self.add_error('last_name', ValidationError('O primeiro nome não pode igual ao sobrenome'))
            
        username = self.cleaned_data.get('username')
        
        try:
            validate_email(username)
        except ValidationError:
            self.add_error('username', ValidationError('Informe um endereço de email válido'))
            
        return super().clean()

Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/user/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth.models import User
from .forms import UserForm
from django.contrib import messages
# Create your views here.

def index(request):
    users = User.objects.all().order_by('-id')
    
    context = {
        'users': users
        }
    
    return render(request, 'users/index.html', context)

def create(request):
    
    form_action = reverse('users:create')
    
    if request.method == 'POST':
        form = UserForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            messages.success(request, 'Usuário cadastrado')
            
            return redirect('users:index')
        
        context = {
        'form': form,
        'form_action': form_action
        }
        
        return render(request, 'users/create.html', context)
            
    
    form = UserForm()
    
    context = {
        'form': form,
        'form_action': form_action
    }
    
    return render(request, 'users/create.html', context)

def update(request):
    return render(request, 'users/create.html')

def delete(request):
    user = get_object_or_404(User, id=id)
    
    user.delete()
    
    return redirect('users:indec')

def login(request):
    return render(request, 'users/login.html')

Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/user/templates/categories/create.html
{% extends "base.html" %} 
{% load static %} 
{% load crispy_forms_tags %}
{% block title %} Categorias{% endblock %} 
{% block content %}
  {% with create_url="/produtos/categorias/cadastro/" %}
    {% if form_action == create_url %}
      <h2 class="mb-3">Cadastro de Categorias</h2>
    {% else %}
      <h2 class="mb-3">Edição de Categoria</h2>
    {% endif %}
    <form action="{{ form_action }}" method="post" novalidate>
      {% csrf_token %}

      <div class="row mb-3">
        <div class="col">
          {{ form.name|as_crispy_field }}
        </div>
      </div>

      <div class="row mb-3">
        <div class="col">
          {{ form.description|as_crispy_field }}
        </div>
      </div>

      <div class="d-grid">
        <button class="btn btn-primary btn-lg">Salvar</button>
      </div>
    </form>
  {% endwith %}
{% endblock %}

Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/user/templates/categories/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Categorias
{% endblock %}
{% block head %}
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
  <script src="{% static 'base/js/index.js' %}"></script>
{% endblock  %}
{% block content %}
  <h2 class="mb-3">Categorias</h2>

  <a 
    href="{% url 'products:category_create' %}" 
    title="Cadastrar nova categoria" 
    class="btn btn-primary btn-sticky-bottom">
    <i class="bi bi-plus"></i>
  </a>

  <!-- Filtro -->
  <form method="get" action="{% url 'products:categories_search' %}" class="row mb-3">
    <div class="col">
      <input value="{{ request.GET.q }}" class="form-control" type="text" name="q" placeholder="Buscar" />
    </div>
    <div class="col-auto">
      <button type="submit" class="btn btn-primary">Buscar</button>
    </div>
  </form>

  <!-- Tabela de estoque -->
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for category in categories %}
          <tr>
            <td>{{ category.id }}</td>
            <td>{{ category.name|title }}</td>
            <td class="d-flex gap-1">
              <a href="{% url 'products:category_update' category.slug %}" class="btn btn-warning btn-sm" title="editar categoria"><i class="bi bi-pencil"></i></a>
              <form method="post" action="{% url 'products:category_delete' category.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm" title="remover categoria"><i class="bi bi-trash"></i></button>
              </form>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="3" class="text-center">Nenhuma categoria cadastrada.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% comment %}Paginação{% endcomment %}
    {% if categories.paginator.num_pages > 1 %}
      <nav aria-label="Paginação da página">
        <ul class="pagination justify-content-end">
          {% if categories.has_previous %}
            <li class="page-item">
              <a href="?page={{ categories.previous_page_number }}&q={{ request.GET.q }}" class="page-link" aria-label="Anterior">&laquo;</a>
            </li>
          {% endif %}
          <li class="page-item active">
            <span class="page-link">{{ categories.number }}</span>
          </li>
          {% if categories.has_next %}
            <li class="page-item">
              <a href="?page={{ categories.next_page_number }}&q={{ request.GET.q }}" class="page-link" aria-label="Próximo">&raquo;</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
  </div>
{% endblock %}