Modulo 8 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/inventory_control/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fornecedores/', include('suppliers.urls')),
    path('produtos/', include('products.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Modulo 8 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
    path("", views.index, name="index"),
    path("cadastro/", views.create, name="create"),
    path("<int:id>/delete", views.delete, name="delete"),
    path("search", views.search, name="search"),
    path("<int:id>/toggle_enabled", views.toggle_enabled, name="toggle_enabled"),
    path("categorias/", views.get_categories, name="categories"),
    path("categorias/cadastro/", views.create_category, name="category_create"),
    path("category/<int:id>/delete", views.delete_category, name="category_delete"),
    path("category/search", views.search_categories, name="categories_search"),
    path("categorias/<slug:slug>/", views.update_category, name="category_update"),
    path("<int:id>/suppliers/", views.get_suppliers_from_product, name = "suppliers"),
    path("<int:id>/delete_supplier/", views.delete_supplier_from_product, name='delete_supplier'),
    path("<slug:slug>/", views.update, name="update"),
]

Modulo 8 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/products/forms.py
from django import forms
from .models import Category, Product, SupplierProduct, ProductInventory
from crispy_forms.helper import FormHelper

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ["thumbnail", "slug", "is_perishable", "suppliers"]
        
        
        labels = {
            "name": "Nome",
            "description": "Descrição",
            "sale_price": "Preço de venda",
            "expiration_date": "Data de expiração",
            "photo": "Imagem do produto",
            "enabled": "Ativo",
            "category": "Categoria",
        }
        
        error_messages = {
            "name": {
                "required": "O campo nome é obrigatório",
                "unique": "Já existe um produto cadastrado com esse nome"
            },
            "description": {
                "required": "O campo descrição é obrigatório",                
            },
            "sale_price": {
                "required": "O campo preço de venda é obrigatório"
            },
        }
        
        widgets = {
            "expiration_date": forms.DateInput(attrs={"type":"date"}, format="%Y-%m-%d")
        }
        
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"
        labels = {
            "name": "Nome",
            "description": "Descrição"
        }
        
        
class SupplierProductForm(forms.ModelForm):
    class Meta:
        model = SupplierProduct
        exclude = ["product"]
        widgets = {
            "cost_price": forms.NumberInput(attrs={"placeholder": "Preço de custo"}),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        
        
SupplierProductFormSet = forms.inlineformset_factory(
    Product, 
    SupplierProduct, 
    form=SupplierProductForm, 
    extra=1, 
    can_delete=True,
    max_num=1
)

class ProductStockForm(forms.ModelForm):
        class Meta:
            model = ProductInventory
            fields = "__all__"
            labels = {
            "product": "Produto",
            "quantity": "Quantidade",
            "local": "Localização"
        }
            
            
ProductInventoryFormSet = forms.inlineformset_factory(
    Product,
    ProductInventory,
    form=ProductStockForm, 
    extra=1, 
    can_delete=True,
    max_num=1
)

    

Modulo 8 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/products/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.http import require_POST, require_GET

from .forms import CategoryForm, ProductForm, SupplierProductFormSet, ProductInventoryFormSet
from .models import Category, Product, SupplierProduct, ProductInventory


def index(request):
    products = Product.objects.order_by("-id")
    stocks = ProductInventory.objects.all()
        
    # Aplicando a paginação
    paginator = Paginator(products, 2)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = { "products": page_obj, 
                "stocks": stocks
               }
    
    return render(request, "products/index.html", context)

def search(request):
    # Obtendo o valor da requisição (Formulário)
    search_value = request.GET.get("q").strip()
    
    # Verificando se algo foi digitado
    if not search_value:
        return redirect("products:index")
    
    # Filtrando os fornecedores
    # O Q é usado para combinar filtros (& ou |)
    products = Product.objects \
        .filter(Q(name__icontains=search_value) | Q(category__name__icontains=search_value)) \
        .order_by("-id")
        
    stocks = ProductInventory.objects.all()
    
    # Criando o paginator
    paginator = Paginator(products, 2)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = { "products": page_obj, 
                "stocks": stocks}
    
    return render(request, "products/index.html", context)

def create(request):
    form_action = reverse("products:create")
    # POST
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        
        if form.is_valid():
            product = form.save()
            
            supplier_product_formset = SupplierProductFormSet(request.POST, instance=product)
            
            if supplier_product_formset.is_valid():
                supplier_product_formset.save()
                
                Stock_form = ProductInventoryFormSet(request.POST, instance=product)
                if Stock_form.is_valid():
                    Stock = Stock_form.save()
                    Stock.product = product 
                    Stock.save()
                    messages.success(request, "O produto foi cadastrado com sucesso!")

                                            
               
            else:
                messages.error(request, "Falha ao cadastrar os fornecedores do produto")
                product.delete()
                
                supplier_product_formset = SupplierProductFormSet(request.POST)
        
                context = { "form": form, "supplier_product_formset": supplier_product_formset, "form_action": form_action }
                
                return render(request, "products/create.html", context)
                
            
            return redirect("products:index")
                
        messages.error(request, "Falha ao cadastrar o produto. Verifique o preenchimento dos campos.")
        
        supplier_product_formset = SupplierProductFormSet(request.POST)
        
        context = { "form": form, "supplier_product_formset": supplier_product_formset, "form_action": form_action }
        
        return render(request, "products/create.html", context)
    
    # GET
    form = ProductForm()
    form_stock = ProductInventoryFormSet()
    supplier_product_formset = SupplierProductFormSet()
    
    context = { "form": form, "supplier_product_formset": supplier_product_formset, "form_action": form_action, "form_stock": form_stock}
    
    return render(request, "products/create.html", context)

def update(request, slug):
    product = get_object_or_404(Product, slug=slug)
    form_action = reverse("products:update", args=(slug,))

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        supplier_product_formset = SupplierProductFormSet(
            request.POST, instance=product)

        if form.is_valid():
            try:
                if form.cleaned_data["photo"] is False:
                    product.thumbnail.delete(save=False)

                form.save()

                if supplier_product_formset.is_valid():
                    supplier_product_formset.save()
                    messages.success(request, "Produto atualizado com sucesso")
                    return redirect("products:index")
                else:
                    messages.error(
                        request, "Falha ao atualizar o produto - Formulário de fornecedores inválido.")

            except IntegrityError:
                messages.error(
                    request, "Falha ao atualizar o produto - Não é possível ter o mesmo fornecedor para o mesmo produto mais de uma vez.")
        else:
            messages.error(
                request, "Falha ao atualizar o produto - Formulário inválido.")
        
        
        supplier_product_formset = SupplierProductFormSet(instance=product)
        context = {
            "form_action": form_action,
            "form": form,
            "supplier_product_formset": supplier_product_formset
        }
        
        return render(request, "products/create.html", context)


    form = ProductForm(instance=product)
    supplier_product_formset = SupplierProductFormSet(instance=product)

    context = {
        "form_action": form_action,
        "form": form,
        "supplier_product_formset": supplier_product_formset
    }

    return render(request, "products/create.html", context)

@require_POST
def delete(request, id):
    product = get_object_or_404(Product, pk=id)
    product.delete()
    
    return redirect("products:index")

@require_POST
def toggle_enabled(request, id):
    product = get_object_or_404(Product, pk=id)
    
    product.enabled = not product.enabled
    product.save()
    
    return JsonResponse({ "message": "success" })


# Categorias
def get_categories(request):
    categories = Category.objects.order_by("-id")
        
    # Aplicando a paginação
    paginator = Paginator(categories, 2)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = { "categories": page_obj }
    
    return render(request, "categories/index.html", context)

def search_categories(request):
    # Obtendo o valor da requisição (Formulário)
    search_value = request.GET.get("q").strip()
    
    # Verificando se algo foi digitado
    if not search_value:
        return redirect("products:categories")
    
    # Filtrando os fornecedores
    # O Q é usado para combinar filtros (& ou |)
    categories = Category.objects \
        .filter(name=search_value) \
        .order_by("-id")
    
    # Criando o paginator
    paginator = Paginator(categories, 2)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = { "categories": page_obj }
    
    return render(request, "categories/index.html", context)

def create_category(request):
    form_action = reverse("products:category_create")
    # POST
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            messages.success(request, "A categoria foi cadastrada com sucesso!")
            
            return redirect("products:categories")
        
        messages.error(request, "Falha ao cadastrar a categoria. Verifique o preenchimento dos campos.")
        
        context = { "form": form, "form_action": form_action }
        
        return render(request, "categories/create.html", context)
    
    # GET
    form = CategoryForm()
    
    context = { "form": form, "form_action": form_action }
    
    return render(request, "categories/create.html", context)

def update_category(request, slug):
    category = get_object_or_404(Category, slug=slug)
    form_action = reverse("products:category_update", args=(slug,)) # Obtendo a URL da rota de atualização
    
    # POST
    if request.method == "POST":
        form = CategoryForm(request.POST, instance=category)
        
        if form.is_valid():                        
            form.save()            
            messages.success(request, "Categoria atualizada com sucesso")            
            return redirect("products:categories")
        
        context = {
            "form_action": form_action,
            "form": form
        }
        
        return render(request, "categories/create.html", context)
    
    # GET
    form = CategoryForm(instance=category)   
    
    context = {
        "form_action": form_action,
        "form": form,
    }
    
    return render(request, "categories/create.html", context)

@require_POST
def delete_category(request, id):
    category = get_object_or_404(Category, pk=id)
    category.delete()
    
    return redirect("products:categories")

@require_POST
def delete_supplier_from_product(request, id):
    supplier_product = get_object_or_404(SupplierProduct, pk=id)
    supplier_product.delete()
    
    return JsonResponse({'message':'success'})

def get_suppliers_from_product(request, id):
    suppliers = SupplierProduct.objects.filter(product__id=id).order_by('-id')
    
    suppliers_serialized = [{
        'id': supplierProduct.id,
        'name': supplierProduct.supplier.fantasy_name,
        'cost_price': supplierProduct.cost_price
    } for supplierProduct in suppliers]
    
    return JsonResponse(suppliers_serialized, safe=False)

Modulo 8 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/products/templates/products/create.html
{% extends "base.html" %} 
{% load static %} 
{% load crispy_forms_tags %}
{% block title %}Cadastro de Produtos{% endblock %} 
{% block head %}
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
  <script src="{% static 'products/js/createUpdate.js' %}"></script>
{% endblock  %}
{% block content %}
  {% with create_url="/produtos/cadastro/" %}
    {% if form_action == create_url %}
      <h2 class="mb-3">Cadastro de Produtos</h2>
    {% else %}
      <h2 class="mb-3">Edição de Produto</h2>
    {% endif %}
    <form action="{{ form_action }}" method="post" enctype="multipart/form-data" novalidate>
      {% csrf_token %}

      <div class="row mb-3">
        <div class="col">
          {{ form.name|as_crispy_field }}
        </div>
      </div>

      <div class="row mb-3">
        <div class="col">
          {{ form_stock.management_form }}
        </div>
      </div>

      {{ form_stock.management_form }}
      {% for stock in form_stock  %}
        <div class="row mb-3">
          {{ stock.id }}
          <div class="col-md-4">
            {{ stock.quantity|as_crispy_field }}
          </div>
          <div class="col-md-8">
            {{ stock.local|as_crispy_field }}
          </div>
        </div>
      {% endfor %}  

      <div class="row mb-3">
        <div class="col-md-4">
          {{ form.category|as_crispy_field }}
        </div>
        <div class="col-md-4">
          {{ form.sale_price|as_crispy_field }}
        </div>
        <div class="col-md-4">
          {{ form.expiration_date|as_crispy_field }}
        </div>
      </div>

      <div class="row mb-3">
        <div class="col">
          {{ form.photo|as_crispy_field }}
        </div>
      </div>

      <h3>Fornecedores</h3>
      <div id="supplierFormset">
        {{ supplier_product_formset.management_form }}
        {% for supplier in supplier_product_formset  %}
          <div class="row mb-3">
            {{ supplier.id }}
            <div class="col-md-5">
              {{ supplier.supplier|as_crispy_field }}
            </div>
            <div class="col-md-5">
              {{ supplier.cost_price|as_crispy_field }}
            </div>
            <div class="col-md-2">
              <div class="d-grid">
                <button {% if supplier.id.value %}data-url="{% url "products:delete_supplier" supplier.id.value %}" {% endif %} type="button" class="btn btn-danger remove-btn">
                  <i class="bi bi-x"></i>
                </button>
              </div>
            </div>
          </div>
        {% endfor %}        
      </div>

      <div class="d-grid mb-3">
        <button type="button" id="addSupplierButton" class="btn btn-outline-secondary">Adicionar fornecedor</button>
      </div>

      <div class="row mb-3">
        <div class="col">
          {{ form.enabled|as_crispy_field }}
        </div>
      </div>

      <div class="d-grid">
        <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
      </div>
    </form>
  {% endwith %}
{% endblock %}

Modulo 8 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/products/templates/products/index.html
{% extends 'base.html' %}
{% load phone_filter %}
{% load static %}
{% block title %}
  Fornecedores
{% endblock %}
{% block head %}
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
  <script src="{% static 'base/js/index.js' %}"></script>
  <script src="{% static 'products/js/index.js' %}"></script>
{% endblock  %}
{% block content %}
  <h2 class="mb-3">Produtos</h2>
  
  <!-- Modal -->
  <div class="modal fade" id="suppliersModal" tabindex="-1" aria-labelledby="suppliersModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="suppliersModalLabel">Fornecedores</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Preço de custo</th>
              </tr>
            </thead>
            <tbody id="suppliersTableBody">

            </tbody>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
        </div>
      </div>
    </div>
  </div>

  <a 
    href="{% url 'products:create' %}" 
    title="Cadastrar novo produto" 
    class="btn btn-primary btn-sticky-bottom">
    <i class="bi bi-plus"></i>
  </a>

  <!-- Filtro -->
  <form method="get" action="{% url 'products:search' %}" class="row mb-3">
    <div class="col">
      <input value="{{ request.GET.q }}" class="form-control" type="text" name="q" placeholder="Buscar" />
    </div>
    <div class="col-auto">
      <button type="submit" class="btn btn-primary">Buscar</button>
    </div>
  </form>

  <!-- Tabela de estoque -->
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>ID</th>
          <th>Foto</th>
          <th>Nome</th>
          <th>Quantidade</th>
          <th>Categoria</th>
          <th>Preço de venda</th>
          <th>Data de expiração</th>
          <th>Ativo</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for product in products %}
          <tr>
            <td>{{ product.id }}</td>
            <td>
              {% if product.thumbnail %}
                <img src="{{ product.thumbnail.url }}" height="30" width="30" alt="{{ product.name }}" class="img-fluid rounded" />
              {% else %}
                Sem foto
              {% endif %}
            </td>
            <td>{{ product.name|title|truncatechars:20 }}</td>
            <td>    
              {% for stock in stocks %}
                {% if stock.product == product %}
                    {{ stock.quantity|floatformat:"2"}}
                {% endif %}
              {% endfor %}
            </td>
            <td>{{ product.category|title|truncatechars:20 }}</td>
            <td>R$ {{ product.sale_price|floatformat:2 }}</td>
            <td>
              {% if product.is_perishable %}
                {{ product.expiration_date|date:"d/m/Y" }}              
              {% else %}
                Não perecível
              {% endif %}
            </td>
            <td>
              <input {% if product.enabled %}checked{% endif %} data-url="{% url 'products:toggle_enabled' product.id %}" type="checkbox" class="form-check-input" />
            </td>
            <td class="d-flex gap-1">
              <button data-url="{% url "products:suppliers" product.id %}" title="fornecedores do produto" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#suppliersModal">
                <i class="bi bi-box"></i>
              </button>
              <a href="{% url 'products:update' product.slug %}" class="btn btn-warning btn-sm" title="editar produto"><i class="bi bi-pencil"></i></a>
              <form method="post" action="{% url 'products:delete' product.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm" title="remover produto"><i class="bi bi-trash"></i></button>
              </form>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="8" class="text-center">Nenhum produto cadastrado.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% comment %}Paginação{% endcomment %}
    {% if products.paginator.num_pages > 1 %}
      <nav aria-label="Paginação da página">
        <ul class="pagination justify-content-end">
          {% if products.has_previous %}
            <li class="page-item">
              <a href="?page={{ products.previous_page_number }}&q={{ request.GET.q }}" class="page-link" aria-label="Anterior">&laquo;</a>
            </li>
          {% endif %}
          <li class="page-item active">
            <span class="page-link">{{ products.number }}</span>
          </li>
          {% if products.has_next %}
            <li class="page-item">
              <a href="?page={{ products.next_page_number }}&q={{ request.GET.q }}" class="page-link" aria-label="Próximo">&raquo;</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
  </div>
{% endblock %}