Modulo 8 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/inventory_control/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fornecedores/', include('suppliers.urls')),
    path('produtos/', include('products.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Modulo 8 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
    path("", views.index, name="index"),
    path("cadastro/", views.create, name="create"),
    path("<int:id>/delete", views.delete, name="delete"),
    path("search", views.search, name="search"),
    path("<int:id>/toggle_enabled", views.toggle_enabled, name="toggle_enabled"),
    path("categorias/", views.get_categories, name="categories"),
    path("categorias/cadastro/", views.create_category, name="category_create"),
    path("category/<int:id>/delete", views.delete_category, name="category_delete"),
    path("category/search", views.search_categories, name="categories_search"),
    path("categorias/<slug:slug>/", views.update_category, name="category_update"),
    path("<int:id>/suppliers/", views.get_suppliers_from_product, name = "suppliers"),
    path("<int:id>/delete_supplier/", views.delete_supplier_from_product, name='delete_supplier'),
    path("<slug:slug>/", views.update, name="update"),
]

Modulo 8 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/suppliers/urls.py
from django.urls import path
from . import views

app_name = "suppliers"
urlpatterns = [
    path("", views.index, name="index"),
    path("cadastro", views.create, name="create"),
    path("<int:id>/delete", views.delete, name="delete"),
    path("search", views.search, name="search"),
    path("<int:id>/toggle_enabled", views.toggle_enabled, name="toggle_enabled"),
    path("<slug:slug>/", views.update, name="update"),
]

Modulo 8 - Django/Aula 02 - Personalizando o Django Admin/inventory_control/base/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      IStock -{% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">

    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'base/js/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'base/js/base.js' %}"></script>

    {% block head %}{% endblock %}
  </head>
  <body>
    <div class="toast-container top-0 end-0 p-3">
      <!-- Then put toasts within -->

      {% for message in messages %}
      <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">          
          <strong class="me-auto">Notificação</strong>
          <small class="text-body-secondary">agora</small>
          <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body">
          {{message}}
        </div>
      </div>   
      {% endfor %}     
    </div>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-3 col-lg-2 d-none d-md-flex flex-column bg-light sidebar flex-shrink-0 p-3">
          <div class="d-flex justify-content-center align-items-center">
            <img src="{% static 'base/img/logo.png' %}" alt="Logo do site" height="70">
            <h1 class="fs-2 px-2">IStock</h1>
          </div>
          <hr>
          <ul class="nav nav-pills flex-column flex-grow-1">
            <li>
              <a href="{% url 'suppliers:index' %}" class="nav-link link-dark">
                <i class="bi bi-box-seam"></i>
                Fornecedores
              </a>
            </li>
            <li>
              <a href="{% url 'products:index' %}" class="nav-link link-dark">
                <i class="bi bi-grid"></i>
                Produtos
              </a>
            </li>
            <li>
              <a href="{% url 'products:categories' %}" class="nav-link link-dark">
                <i class="bi bi-tag"></i>
                Categorias
              </a>
            </li>
          </ul>
          <hr>
          <ul class="nav nav-pills">
            <li>
              <a href="#" class="nav-link link-dark">
                <i class="bi bi-box-arrow-left"></i>
                Sair
              </a>
            </li>
          </ul>
        </nav>

        <main class="col-md-9 col-lg-10 ml-sm-auto p-md-4 overflow-auto">
          <div class="container mt-4">
            {% block content %}{% endblock  %}
          </div>
        </main>
      </div>
    </div>
  </body>
</html>