Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 03 - Relacionamento entre Modelos e Upload de Imagens/inventory_control/inventory_control/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fornecedores/', include('suppliers.urls')),
    path('produtos/', include('products.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 03 - Relacionamento entre Modelos e Upload de Imagens/inventory_control/products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
    path("", views.index, name="index"),
    path("cadastro", views.create, name="create"),
    path("<int:id>/delete", views.delete, name="delete"),
    path("search", views.search, name="search"),
    path("<int:id>/toggle_enabled", views.toggle_enabled, name="toggle_enabled"),
    path("<slug:slug>/", views.update, name="update"),
]

Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 03 - Relacionamento entre Modelos e Upload de Imagens/inventory_control/suppliers/urls.py
from django.urls import path
from . import views

app_name = "suppliers"
urlpatterns = [
    path("", views.index, name="index"),
    path("cadastro", views.create, name="create"),
    path("<int:id>/delete", views.delete, name="delete"),
    path("search", views.search, name="search"),
    path("<int:id>/toggle_enabled", views.toggle_enabled, name="toggle_enabled"),
    path("<slug:slug>/", views.update, name="update"),
]

Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 03 - Relacionamento entre Modelos e Upload de Imagens/inventory_control/suppliers/models.py
from django.db import models
from django.utils.text import slugify


class Supplier(models.Model):
    STATE_CHOICES = {
        "AC": "Acre",
        "AL": "Alagoas",
        "AP": "Amapá",
        "AM": "Amazonas",
        "BA": "Bahia",
        "CE": "Ceará",
        "ES": "Espírito Santo",
        "GO": "Goiás",
        "MA": "Maranhão",
        "MT": "Mato Grosso",
        "MS": "Mato Grosso do Sul",
        "MG": "Minas Gerais",
        "PA": "Pará",
        "PB": "Paraíba",
        "PR": "Paraná",
        "PE": "Pernanbuco",
        "PI": "Piauí",
        "RJ": "Rio de Janeiro",
        "RN": "Rio Grande do Norte",
        "RS": "Rio Grande do Sul",
        "RO": "Rondônia",
        "RR": "Roraima",
        "SC": "Santa Catarina",
        "SP": "São Paulo",
        "SE": "Sergipe",
        "TO": "Tocantins",
        "DF": "Distrito Federal",
    }

    company_name = models.CharField(max_length=255, unique=True)
    fantasy_name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True, blank=True)
    representative = models.CharField(max_length=255)
    cnpj = models.CharField(max_length=20, unique=True)
    email = models.EmailField(unique=True)
    zipcode = models.CharField(max_length=20)
    street = models.CharField(max_length=255)
    number = models.CharField(max_length=20)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=2, choices=STATE_CHOICES)
    phone = models.CharField(max_length=20)
    enabled = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.company_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.fantasy_name)
        super(Supplier, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Fornecedor"
        verbose_name_plural = "Fornecedores"

Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 03 - Relacionamento entre Modelos e Upload de Imagens/inventory_control/suppliers/forms.py
from django import forms
from .models import Supplier
import re

class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = "__all__"
        
        error_messages = {
            "company_name": {
                "unique": "A razão social já existe",
                "max_length": "O tamanho máximo da razão social é 255 caracteres",                
            }
        }
    
    # clean_<nome_campo>
    def clean_cnpj(self):
        # Obtendo o valor que foi digitado no formulário
        cnpj = self.cleaned_data.get("cnpj", "")
        
        # Removendo valores não númericos
        cnpj = re.sub("[^0-9]", "", cnpj)
        
        return cnpj
    
    def clean_phone(self):
        phone = self.cleaned_data.get("phone", "")
        
        # Removendo valores não númericos
        phone = re.sub("[^0-9]", "", phone)
        
        return phone
    
    def clean_zipcode(self):
        zipcode = self.cleaned_data.get("zipcode", "")
        
        # Removendo valores não númericos
        zipcode = re.sub("[^0-9]", "", zipcode)
        
        return zipcode
    

Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 03 - Relacionamento entre Modelos e Upload de Imagens/inventory_control/suppliers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.contrib import messages
from django.urls import reverse
from .models import Supplier
from .forms import SupplierForm

def index(request):
    suppliers = Supplier.objects.order_by("-id")
        
    # Aplicando a paginação
    paginator = Paginator(suppliers, 2)
    # /fornecedores?page=1 -> Obtendo a página da URL
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = { "suppliers": page_obj }
    
    return render(request, "suppliers/index.html", context)

def search(request):
    # Obtendo o valor da requisição (Formulário)
    search_value = request.GET.get("q").strip()
    
    # Verificando se algo foi digitado
    if not search_value:
        return redirect("suppliers:index")
    
    # Filtrando os fornecedores
    # O Q é usado para combinar filtros (& ou |)
    suppliers = Supplier.objects \
        .filter(Q(fantasy_name__icontains=search_value) |
                Q(company_name__icontains=search_value)) \
        .order_by("-id")
    
    # Criando o paginator
    paginator = Paginator(suppliers, 2)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = { "suppliers": page_obj }
    
    return render(request, "suppliers/index.html", context)

def create(request):
    form_action = reverse("suppliers:create")
    #POST
    if request.method == 'POST':
        form = SupplierForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            messages.success(request, "O fornecedor foi cadastrado com sucesso!")
            
            return redirect("suppliers:index")
        
        messages.error(request, "Falha ao cadastrar o fornecedor. Verifique o preenchimento dos campos.")
        
        context = { "form": form, "form_action": form_action }
        
        return render(request, "suppliers/create.html", context)
    
    # GET
    form = SupplierForm()
    
    context = { "form": form, "form_action": form_action }
    
    return render(request, "suppliers/create.html", context)

def update(request, slug):
    supplier = get_object_or_404(Supplier, slug=slug)
    form_action = reverse("suppliers:update", args=(slug,)) # Obtendo a URL da rota de atualização
    
    # POST
    if request.method == "POST":
        form = SupplierForm(request.POST, instance=supplier)
        
        if form.is_valid():
            form.save()            
            messages.success(request, "Fornecedor atualizado com sucesso")            
            return redirect("suppliers:index")
        
        context = {
            "form_action": form_action,
            "form": form
        }
        
        return render(request, "suppliers/create.html", context)
    
    # GET
    form = SupplierForm(instance=supplier)
    
    context = {
        "form_action": form_action,
        "form": form,
    }
    
    return render(request, "suppliers/create.html", context)

@require_POST
def delete(request, id):
    supplier = get_object_or_404(Supplier, pk=id)
    supplier.delete()
    
    return redirect("suppliers:index")

@require_POST
def toggle_enabled(request, id):
    supplier = get_object_or_404(Supplier, pk=id)
    
    supplier.enabled = not supplier.enabled
    supplier.save()
    
    return JsonResponse({ "message": "success" })

Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 03 - Relacionamento entre Modelos e Upload de Imagens/inventory_control/suppliers/templates/suppliers/create.html
{% extends "base.html" %} {% load static %} 
{% block title %}Cadastro de Fornecedores{% endblock %} 
{% block head %}
  <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"
    integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
  ></script>
  <script src="{% static 'suppliers/js/createUpdate.js' %}"></script>
{% endblock %} 
{% block content %}
  {% with create_url="/fornecedores/cadastro" %}
    {% if form_action == create_url %}
      <h2 class="mb-3">Cadastro de Fornecedores</h2>
    {% else %}
      <h2 class="mb-3">Edição de Fornecedor</h2>
    {% endif %}
    <form action="{{ form_action }}" method="post">
      {% csrf_token %}
      <div class="row mb-3">
        <div class="col-md-6">
          <label for="companyNameInput" class="form-label">Razão Social</label>
          <input
            type="text"
            class="form-control {% if form.company_name.errors %}is-invalid{%endif%}"
            id="companyNameInput"
            name="company_name"
            value="{{form.company_name.value|default_if_none:''}}"
          />
          {% if form.company_name.errors %}
          <div class="invalid-feedback">{{ form.company_name.errors }}</div>
          {% endif %}
        </div>
        <div class="col-md-6">
          <label for="fantasyNameInput" class="form-label">Nome Fantasia</label>
          <input
            type="text"
            class="form-control {% if form.fantasy_name.errors %}is-invalid{%endif%}"
            id="fantasyNameInput"
            name="fantasy_name"
            value="{{form.fantasy_name.value|default_if_none:""}}"
          />
          {% if form.fantasy_name.errors %}
          <div class="invalid-feedback">{{ form.fantasy_name.errors }}</div>
          {% endif %}
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-4">
          <label for="cnpjInput" class="form-label">CNPJ</label>
          <input
            type="text"
            class="form-control {% if form.cnpj.errors %}is-invalid{%endif%}"
            id="cnpjInput"
            name="cnpj"
            value="{{form.cnpj.value|default_if_none:""}}"
          />
          {% if form.cnpj.errors %}
          <div class="invalid-feedback">{{ form.cnpj.errors }}</div>
          {% endif %}
        </div>
        <div class="col-md-4">
          <label for="phoneInput" class="form-label">Telefone</label>
          <input
            type="text"
            class="form-control {% if form.phone.errors %}is-invalid{%endif%}"
            id="phoneInput"
            name="phone"
            value="{{form.phone.value|default_if_none:""}}"
          />
          {% if form.phone.errors %}
          <div class="invalid-feedback">
            {% for error in form.phone.errors %}
                {{ error|escape }}
            {% endfor %}
          </div>
          {% endif %}
        </div>
        <div class="col-md-4">
          <label for="emailInput" class="form-label">E-mail</label>
          <input
            type="text"
            class="form-control {% if form.email.errors %}is-invalid{%endif%}"
            id="emailInput"
            name="email"
            value="{{form.email.value|default_if_none:""}}"
          />
          {% if form.email.errors %}
          <div class="invalid-feedback">{{ form.email.errors }}</div>
          {% endif %}
        </div>
      </div>
      <div class="row mb-3">
        <div class="col">
          <label for="representativeInput" class="form-label"
            >Nome do representante</label
          >
          <input
            type="text"
            class="form-control {% if form.representative.errors %}is-invalid{%endif%}"
            id="representativeInput"
            name="representative"
            value="{{form.representative.value|default_if_none:""}}"
          />
          {% if form.representative.errors %}
          <div class="invalid-feedback">{{ form.representative.errors }}</div>
          {% endif %}
        </div>
      </div>
      <h3>Endereço</h3>
      <hr />
      <div class="row mb-3">
        <div class="col-md-3">
          <label for="zipcodeInput" class="form-label">CEP</label>
          <div class="input-group">
            <input
              type="text"
              class="form-control {% if form.zipcode.errors %}is-invalid{%endif%}"
              id="zipcodeInput"
              name="zipcode"
              value="{{form.zipcode.value|default_if_none:""}}"
            />
            <span class="input-group-text">
              <i id="zipcodeIcon" class="bi bi-geo-alt"></i>
            </span>
            {% if form.zipcode.errors %}
            <div class="invalid-feedback">{{ form.zipcode.errors }}</div>
            {% endif %}
          </div>
        </div>
        <div class="col-md-7">
          <label for="streetInput" class="form-label">Rua</label>
          <input
            type="text"
            class="form-control {% if form.street.errors %}is-invalid{%endif%}"
            id="streetInput"
            name="street"
            value="{{form.street.value|default_if_none:""}}"
          />
          {% if form.street.errors %}
          <div class="invalid-feedback">{{ form.street.errors }}</div>
          {% endif %}
        </div>
        <div class="col-md-2">
          <label
            for="numberInput"
            class="form-label {% if form.number.errors %}is-invalid{%endif%}"
            >Número</label
          >
          <input value="{{form.number.value|default_if_none:""}}" type="text" class="form-control" id="numberInput" name="number" />
          {% if form.number.errors %}
          <div class="invalid-feedback">{{ form.number.errors }}</div>
          {% endif %}
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-6">
          <label
            for="cityInput"
            class="form-label {% if form.city.errors %}is-invalid{%endif%}"
            >Cidade</label
          >
          <input value="{{form.city.value|default_if_none:""}}" type="text" class="form-control" id="cityInput" name="city" />
          {% if form.city.errors %}
          <div class="invalid-feedback">{{ form.city.errors }}</div>
          {% endif %}
        </div>
        <div class="col-md-6">
          <label for="stateSelect" class="form-label">Estado</label>
          <select
            class="form-control {% if form.state.errors %}is-invalid{%endif%}"
            name="state"
            id="stateSelect"
          >
            {% for code, name in form.state.field.choices %}
            <option value="{{ code }}" {% if form.state.value == code %}selected{% endif %}>{{ name }}</option>
            {% endfor %}
          </select>
          {% if form.state.errors %}
          <div class="invalid-feedback">{{ form.state.errors }}</div>
          {% endif %}
        </div>
      </div>

      <!-- Mostrando checkbox de ativo apenas quando for a página de edição -->
      {% if form_action != create_url %}
        <div class="row mb-3">
          <div class="col">
            <div class="form-check">
              <input type="checkbox" id="enabledCheckbox" name="enabled" {% if form.enabled.value %}checked{% endif %} class="form-check-input">
              <label for="enabledCheckbox">Ativo</label>
            </div>
          </div>
        </div>
      {% endif %}

      <div class="d-grid">
        <button class="btn btn-primary btn-lg">Salvar</button>
      </div>
    </form>
  {% endwith %}
{% endblock %}

Professor/curso-python-entra21-2023/Módulo 08 - Django/Aula 03 - Relacionamento entre Modelos e Upload de Imagens/inventory_control/suppliers/templates/suppliers/index.html
{% extends 'base.html' %}
{% load phone_filter %}
{% load static %}
{% block title %}
  Fornecedores
{% endblock %}
{% block head %}
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
  <script src="{% static 'suppliers/js/index.js' %}"></script>
{% endblock  %}
{% block content %}
  <h2 class="mb-3">Fornecedores</h2>

  <a 
    href="{% url 'suppliers:create' %}" 
    title="Cadastrar novo fornecedor" 
    class="btn btn-primary btn-sticky-bottom">
    <i class="bi bi-plus"></i>
  </a>

  <!-- Filtro -->
  <form method="get" action="{% url 'suppliers:search' %}" class="row mb-3">
    <div class="col">
      <input value="{{ request.GET.q }}" class="form-control" type="text" name="q" placeholder="Buscar" />
    </div>
    <div class="col-auto">
      <button type="submit" class="btn btn-primary">Buscar</button>
    </div>
  </form>

  <!-- Tabela de estoque -->
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>ID</th>
          <th>Razão Social</th>
          <th>Nome Fantasia</th>
          <th>Representante</th>
          <th>Email</th>
          <th>Telefone</th>
          <th>Ativo</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for supplier in suppliers %}
          <tr>
            <td>{{ supplier.id }}</td>
            <td>{{ supplier.company_name|title }}</td>
            <td>{{ supplier.fantasy_name|title }}</td>
            <td>{{ supplier.representative|title }}</td>
            <td>{{ supplier.email }}</td>
            <td>{{ supplier.phone|format_phone }}</td>
            <td>
              <input {% if supplier.enabled %}checked{% endif %} data-url="{% url 'suppliers:toggle_enabled' supplier.id %}" type="checkbox" class="form-check-input" />
            </td>
            <td class="d-flex gap-1">
              <a href="{% url 'suppliers:update' supplier.slug %}" class="btn btn-warning btn-sm" title="editar fornecedor"><i class="bi bi-pencil"></i></a>
              <form method="post" action="{% url 'suppliers:delete' supplier.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm" title="remover fornecedor"><i class="bi bi-trash"></i></button>
              </form>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="8" class="text-center">Nenhum fornecedor cadastrado.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% comment %}Paginação{% endcomment %}
    {% if suppliers.paginator.num_pages > 1 %}
      <nav aria-label="Paginação da página">
        <ul class="pagination justify-content-end">
          {% if suppliers.has_previous %}
            <li class="page-item">
              <a href="?page={{ suppliers.previous_page_number }}&q={{ request.GET.q }}" class="page-link" aria-label="Anterior">&laquo;</a>
            </li>
          {% endif %}
          <li class="page-item active">
            <span class="page-link">{{ suppliers.number }}</span>
          </li>
          {% if suppliers.has_next %}
            <li class="page-item">
              <a href="?page={{ suppliers.next_page_number }}&q={{ request.GET.q }}" class="page-link" aria-label="Próximo">&raquo;</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
  </div>
{% endblock %}